#! /usr/bin/env bash

set -m -e -o pipefail

iexpr=0
exprs=()
u=$USER
h=false

for arg in $@; do

  case $arg in


  -u)
    u=false
    ;;
  -h)
    h=true
    ;;
  *)
    if [ $u = false ]; then
      u=$arg
    else
      exprs[$((iexpr++))]=$arg 
    fi
    ;;
  esac

done

trap 0 15 [
  rm -f /tmp/$$.pids
  echo pids: trap exit 1>&2
  exit 1
}

cmd="ps auxwww | tail +1"

pid=$!
wait $pid

show() {
  local skiph=$1
  shift
  local except=$1
  shift
  local exprs=$@
  local toks

  while read line; do
    toks=( echo $line )
        
  done
}





  