#! /usr/bin/env bash

if [ "$1" != "child" ]; then
  eval "$0 child $@ </dev/null 1>/dev/null 2>/dev/null" &
  fstatus=$?
  pid=$!
  ps -fp $pid >/dev/null
  status=$?
  if [ $status -ne 0 ]; then
    echo $0: failed on fork $fstatus pid $$ child $pid 1>&2
  fi
  exit $status
fi

shift
set -e -o pipefail

n=8
if [ "$1" != "" ]; then
  n=$1
fi

while true; do
  u=$(uptime)
  u=${u/* /}
  u=${u/.*/}
  if [ $u -lt $n ]; then
    echo load $u is below $n on host $(hostname) | mail akimball2@bloomberg.net
    exit 0
  fi  
  sleep 60
done
exit 1

