#! /usr/bin/env bash
set +o pipefail

convw() {
  echo $@ | sed -e 's,\\x,,g' | xxd -r -p | iconv -f utf-8 -t ucs-2 | \
    dd bs=2 conv=swab 2>/dev/null | xxd -p
  return $?
}

conv(){
  out=""
  for arg in $@; do
    out="$out $(convw $arg)"
  done
  echo $out
  test ! -z $out
  return $?
}

sedfmt=false
args=""
for arg in $@; do
  case $arg in
  -e)
    sedfmt=true
    ;;
  *)
    args="$args $arg"
    ;;
  esac
done

if [ -z "$args" ]; then
  rv=0
  while read line; do
    if $sedfmt; then
      conv $line | sed -e 's,\([a-f0-9][a-f0-9][a-f0-9][a-f0-9]\),\\u\1,g'
    else
      conv $line
    fi
    rv=$((rv + $?))
  done
else 
  if $sedfmt; then
    eval "conv $args | sed -e 's,\([a-f0-9][a-f0-9][a-f0-9][a-f0-9]\),\\\\u\1,g'"
  else
    eval "conv $args"
  fi
  rv=$?  
fi

exit $rv
