#! /usr/bin/env bash
set +o pipefail

convw() {
  echo $@ | xxd -r -p | dd bs=2 conv=swab 2>/dev/null | iconv -f ucs-2 -t utf-8 | xxd -p
  return $?
}

conv(){
  out=""
  for arg in $@; do
    out="$out $(convw $arg)"
  done
  echo $out
  test ! -z $out
  return $?
}

if [ -z "$@" ]; then
  rv=0
  while read line; do
    conv $line
    rv=$((rv + $?))
  done
else 
  conv $@
  rv=$?  
fi

exit $rv
for arg in $@; do

done
